stages:
  - test
  - build
  - publish

npm-lint:
  image: node:10-alpine
  stage: test
  script:
    - npm install
    - npm run lint

npm-test:
  image: node:10-alpine
  stage: test
  script:
    - npm install
    - npm run test

npm-test:e2e:
  image: node:10-alpine
  stage: test
  services:
    - name: registry.gitlab.com/wonderboisse/eureka/master:2a464f552a8cb605a8cea9b2bc73c107162ac675
      alias: eureka-service
  script:
    - npm install
    - npm run test:e2e

npm-build:
  image: node:10-alpine
  stage: build
  artifacts:
    expire_in: 30 mins
    paths:
      - dist
  script:
    - npm install
    - npm run build

npm-publish:
  image: node:10-alpine
  stage: publish
  only:
    - tags
  script:
    - npm version --allow-same-version --no-git-tag-version ${CI_COMMIT_REF_NAME}
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
